### ISSUE TITLE
Invalid security token error on Statistics page

### ISSUE THREAD

**Issue by arvislacis** [wintercms/wn-redirect-plugin#2]
With latest changes on 1.1.8-dev branch (probably because of https://github.com/wintercms/winter/commit/f79e672a13404bd1bbba6bd0d182fc1fdcdd08e2) it's not possible to view Statistics page of plugin, the AJAX handler error pop-up is shown:

![2022-05-22_19-13](https://user-images.githubusercontent.com/626982/169705109-d665fd7a-975a-440c-b630-891c131c0c85.png)

With message "Invalid security token error" and no data is shown/returned (loading indicators are spinning forever).

This happens because on Statistics page AJAX POST requests are made to gather the information so the following check fails:

https://github.com/wintercms/winter/blob/0c5099f0b102fc43634bce01cfeafb1763a39251/modules/backend/classes/Controller.php#L207

**Comment by LukeTowers** [comment]
I can confirm that this is an issue, the statistics page makes several requests via the JS Ajax api `$.request()` all without targeting an element or being within a form element with the required session token hidden input. This is supposed to be handled by backend.js grabbing the token from the meta tag in head. 

@bennothommo found that it's a race condition that occurs because the new ajaxPrefilter isn't setup until the ready event is fired, but these widgets are making requests before that event is fired. He should have a fix shortly.

Eventually I'll just replace this implementation entirely by using the (soon to be added) DashboardController behaviour

**Comment by bennothommo** [comment]
Fixed by https://github.com/wintercms/winter/commit/e32ebdfb809d71f4b1cb1f3e2cfd8252ed0266da
